### ISSUE TITLE
Syncing a remote copy group with skip initial sync set to true and full sync set to true fails the playbook with an incorrect error msg

### ISSUE THREAD

**Issue by leenaj0hn** [HewlettPackard/hpe3par_ansible_module#49]
While adding a volume to remote copy group set skip initial sync value to true.
And while syncing a remote copy group set the full sync value to true. The playbook fails with a generic error message. 

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "admit_volume_targets": null,
            "different_secondary_wwn": false,
            "discard_new_data": false,
            "domain": null,
            "full_sync": false,
            "keep_snap": false,
            "local_groups_direction": false,
            "local_remote_volume_pair_list": [],
            "local_snap_cpg": null,
            "local_user_cpg": null,
            "modify_targets": null,
            "no_resync_snapshot": false,
            "no_snapshot": false,
            "recovery_action": null,
            "remote_copy_group_name": "ansible_CreateRCG-003",
            "remote_copy_targets": null,
            "remove_secondary_volume": false,
            "skip_initial_sync": true,
            "skip_promote": false,
            "skip_start": false,
            "skip_sync": false,
            "snapshot_name": null,
            "source_port": null,
            "starting_snapshots": [
                {
                    "snapshotName": "Ansible_volume_SS_snap_01",
                    "volumeName": "Ansible_volume_01"
                }
            ],
            "state": "start",
            "stop_groups": false,
            "storage_system_ip": "192.168.67.7",
            "storage_system_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "storage_system_username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "target_mode": null,
            "target_name": "CSSOS-SSA05",
            "target_port_wwn_or_ip": null,
            "unset_snap_cpg": false,
            "unset_user_cpg": false,
            "volume_auto_creation": false,
            "volume_name": null
        }
    },
    **"msg": "Start Remote Copy Group failed | Bad request (HTTP 400) 44 - invalid input: parameters cannot be present at the same time"**

**Comment by ansarars** [comment]
Issue is not reproduced on my system.

**Comment by ansarars** [comment]
It is observed that skip_initial_sync is set to true while adding volume to remote copy group using below property file add_vol_rcg_ts10_properties.yml:-
storage_system_ip: "192.168.67.7"
storage_system_username: "3paradm"
storage_system_password: "3pardata"
remote_copy_group_name: "ansible_CreateRCG-003"
state: add_volume
volume_name: "Ansible_volume_01"
admit_volume_targets:
- target_name: "CSSOS-SSA05"
   sec_volume_name: "Sec_vol_1"
snapshot_name:
volume_auto_creation:
skip_initial_sync: "true"
different_secondary_wwn:

Since volume add and start remote copy operations are performed in same playbook sync_rcg_ts03_playbook.yml, hence skip_initial_sync value will be true in case when you are starting remote copy group.

It is observed that while starting remote copy group you have given snapshotName in start_rcg_ts07_v1_properties.yml file as given below, While it is documented in wsapi that if snapshotName is given then skip_initial_sync value can’t be true. 

Hence you will have to provide entry skip_initial_sync: False in below  property file start_rcg_ts07_v1_properties.yml
storage_system_ip: 192.168.67.7
storage_system_password: 3pardata
storage_system_username: 3paradm
remote_copy_group_name: ansible_CreateRCG-003
starting_snapshots:
- volumeName: Ansible_volume_01
   snapshotName: Ansible_volume_SS_snap_01
state: start
target_name: CSSOS-SSA05

Conclusion: Issue-49 doest require code changes. It only requires entry of skip_initial_sync: False in property file start_rcg_ts07_v1_properties.yml

**Comment by prablr79** [comment]
invalid defect.  its only playbook issue.  @leenaj0hn please verify and close this.

**Comment by leenaj0hn** [comment]
Closing this issue
